language: python
python:
  - '3.6'
sudo: required

install:
  - pip3 install ansible 'molecule[ec2]<3.0' ansible-lint boto boto3

script:
  - ansible --version
  - molecule --version
  - molecule test -s aws-ec2

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

env:
  global:
    - EC2_REGION: eu-west-1 
    - secure: W4toFSCW5T+rfl56A8Hc2HSp7VDt76/aHB+PiSsL4RdOVWVLz3x5nxVxNbGzK1YtOF+S+/PPu5E+vx71slAWtzpqwd0+e2N08OfEJ27+t6fnzlXcd6SZrQTKeA6BVUNrbUhQ2yhuQsPqNMJF6CI7cG8NbBlz0XZh/lE5rlFqnAdcQhsmWIxuufNZ8zLLrYJlx2AB0iJ7LMc14iGKq6zSLXkKCiN399R8xIm1EQWY5U0Q27QcPv1jI0Qx2UVjouwnMzvHit1Ev+pH0/3Is4gQPB6iRyhqtnac0CSipudyqK0pJRXWnj/bedypAqN78oeEwwp9g4cVTdcdENnXISNIihW1+4euhc78R6ocxmqvmjjVSYYdrPHdr2NKtGV53i5BIfGbaHYe7nQZMJNVkoJgUG6jrTIonBIMw6JdM8vFqjqK7uEC/MuQXo42RU1S/eYntB7R0hcCL4jRg5k1SVnA6cfUN2VqGKtZbFl1Mp5acBC5npBFhkRMH426T/lH05DSziZjZOqkeB/q98UoeIMyPgee26Cz5VcO2fBc6Xoprk4ko0Gj/o0ebqF7ryO8OSXK5tKKc+bAtYE+9NcrhKIB8Pt33pcVfUDKkdpmjFAYm4MRHhzKuNPRvoKq6PH74vkcDWn93Y3K8M6T7PL5MnO7UjxN8LfsxbhEQ06p8ORbcwE=
    - secure: gQWrRmAlzii5aCYOaUzmFVj55GTlh7DQZVEHArR+szM/G9JO4L/ZppLvwEhNyUbucXgqFLkJcFk9BnfISENw0KWI/wrHR1Pd+rPj2USY6L/o+4OdKaBOkZ8byXQ84504oT1kLOMkMomFsjDMNdxqEp6UKvjAEHrr0Pz+xVgKX9qV472jLKJe16VtYvmCN2xGsl/2sBghd08Pl1WJ+P1Vh/FWFcPlma/tLGpKHxTnXClvH8i+OIcYygcxenu1g4FB40wbr1V4w9LdtzjRp6Ss2ct/7SfDMfx3FtXHUxcQpsB23JqXp4ZVzxaoVml/LF4ke9ekS93Pd1lKTRGu6XeIMTQV4SqwJ+PLc4wqRtACA5zeBkiIbqE1r+r4tLCtbr5Ix14SRUWuoQ+KMSEpatPHKcD2EiM9xWg8H6lS50XNjjpqsBBDXPbwZw2yyHTaecDxxK9hHTuTurk389LV7p5iTvqIL3itkCwQWtERoPsRdu9zPjmoqdWfNLN70wtztO4b0P/supWA43E4TbS4qSckCSqoNYKyYPmeo6/9jjMEzJ87fT4btBrprq0J9OdQjv/H1a8JLicSKf/ed3Z6CXJHuhvzwzkCU1n8ZtlyWre+A2FzOlj8PePbUM2D6PGrYRKSTedAr6TIHf9JB3m5vGKiK/VQnqYp4Ck9hV4m7aktSzE=
